 plugins: [
                "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "table contextmenu directionality emoticons template textcolor paste fullpage textcolor"
        ]

toolbar1: styleselect | bold italic | link image | undo redo
toolbar2: table | fullscreen
plugins:
  - table
  - fullscreen